version: "3.9"
services:
  backend:
    image: video
    container_name: video
    restart: always
    ports:
      - "80:8080"
    environment:
      SPRING_PROFILES_ACTIVE: master
      SERVER_PORT: 8080
      POSTGRES_DB: jdbc:postgresql://database:5432/postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: aliaskar03
  database:
    image: postgres:15
    restart: always
    container_name: database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: aliaskar03
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data: